---
platform: linux
image_resource:
  type: docker-image
  source: 
    repository: springio/spring-ci-base
inputs:
  - name: source
run:
  dir: source/complete
  path: ./mvnw
  args:
  - install
params:
  TERM: dumb